### ISSUE TITLE
ロゴを考える

### ISSUE THREAD

**Issue by miya0001** [space-apps-kushimoto/handbook#1]
NASA からガイドラインが来ていないので最終的なロゴはまだ無理。（たとえばポスター等）
暫定的なものをとりあえず作って、あとで変更する？

**Comment by miya0001** [comment]
とりあえず今必要なロゴの使いみちは以下。

* Facebook及びtwitterなどのソーシャルアカウトのアバター（正方形のもの）
* 公式サイト

**Comment by kwaka1208** [comment]
SNSで使うのであれば、正円に収まるもの（円形でなくてもよい）の方が良いと思います。

**Comment by miya0001** [comment]
Related: https://github.com/space-apps-kushimoto/space-apps-kushimoto.github.io/issues/2
