### ISSUE TITLE
学生のスタッフに対する交通費の支給等を検討する

### ISSUE THREAD

**Issue by miya0001** [space-apps-kushimoto/handbook#10]

**Comment by kwaka1208** [comment]
5月のMaker Faire Kyoto 2019で開催した子どもプログラミング喫茶では、学生さんのみ交通費の支給を行いました。最寄り駅を聞いて、そこから一番妥当ならルートでの金額を出して、それを当日現金で渡す形にしました。

**Comment by nztm** [comment]
新大阪からくろしおで串本まで行くのに、始発に乗っても11時03分着のようです。
NASA Space Apps Challenge自体は、10月18日の何時頃から始まるのでしょうか。

宿泊施設までの移動の件もありますし、
それによって、県外参加者の範囲を決める必要があるかもしれません。

https://www.jorudan.co.jp/time/cgi/time.cgi?eki1=%E6%96%B0%E5%A4%A7%E9%98%AA&Csg=1&Sok=1&rnm=%E3%81%8F%E3%82%8D%E3%81%97%E3%81%8A&pg=0&Dym=201910&Ddd=18&btn=%E3%80%80%E5%A4%89%E6%9B%B4%E3%80%80

**Comment by kwaka1208** [comment]
この情報もWikiにまとめておきますが、参加者募集についてはこちらのconnpassを使っています。
https://spaceappsjapan.connpass.com/

スタート時刻は各地域ごとに決めて構いません。串本の場合は、宿泊が前提になるのであれば夜遅くシフトするという考え方もありかなと思いますので、スタートを遅くするという考え方もあると思います。
