### ISSUE TITLE
ボランティアの申込みフォーム

### ISSUE THREAD

**Issue by miya0001** [space-apps-kushimoto/handbook#11]
ボランティアの参加申込フォームをつくりました。
チェックお願いします。
https://docs.google.com/forms/d/1aouKsDi4XNUdj7JmU80kiMu3jKVgO4dp1rGV2cCyajM/viewform?edit_requested=true

**Comment by kwaka1208** [comment]
GitHubとかGoogleアカウントは確定してから確認しますか？
GitHubアカウントぐらいなら先に聞いておいてもいいかなぁとか。

**Comment by miya0001** [comment]
SNS アカウントは確かに迷いどころですよね。当日ボランティアの募集のハードルを上げるかなーと思って迷ってるんですよね。

**Comment by miya0001** [comment]
当日ボランティアは直前に別途募集するという手もあるか。。。

**Comment by kwaka1208** [comment]
当日ボランティアは、もうちょっと見えてからでもいいかもですね。実際、そんなにはいらないですよ。

**Comment by kwaka1208** [comment]
各種アカウントの確認は、参加が確定してからでもいいかもしれませんね。それはそれで別フォーム作ればいいか。
