### ISSUE TITLE
想定人数の算出

### ISSUE THREAD

**Issue by kwaka1208** [space-apps-kushimoto/handbook#13]
会場規模とか宿泊施設の確保のため、予定チーム数と各チームの人数を決めて想定人数を決める必要があります。
例えば、5チームで4名/チームだったら20名、+スタッフ10名で30名とか。
部屋は男女で分ける必要があるので、そこの想定もある程度必要ですね。

ちなみに、昨年の大阪は少なめで27名でした。
https://spaceappsjapan.connpass.com/event/101901/

これぐらいの規模は集めたいとかあれば、コメントお願いします。

**Comment by miya0001** [comment]
最低で50人以上は必須です。（助成金の関係で）

7月から僕と山本さんが参加しているIT教育が再開しますので、そこから地元の中高に参加をお願いできると思います。

このあたりどう設計するかを近々ブレストしたほうがいいかもですね。

**Comment by kwaka1208** [comment]
なるほど、それはスタッフを含めですか？それとも純粋な参加者の人数で？

**Comment by miya0001** [comment]
スタッフを含めてでいいかなと思います。

**Comment by miya0001** [comment]
できればご家族もふくめて100人ぐらいを目標にできないかなと。
