### ISSUE TITLE
Facebook ページ

### ISSUE THREAD

**Issue by miya0001** [space-apps-kushimoto/handbook#3]
* カバー画像をつくる
* 各種の設定をおこなって公開する

**Comment by kwaka1208** [comment]
管理者も複数追加した方がいいかもですね。

**Comment by miya0001** [comment]
はい、担当わけしたいですね。

**Comment by kwaka1208** [comment]
私、入れてもらって構わないので突っ込んでください。なかなか現地（串本）での活動には入れないのでオンラインでできることを中心にサポートします。
