### ISSUE TITLE
スタッフ用のドキュメント

### ISSUE THREAD

**Issue by miya0001** [space-apps-kushimoto/handbook#5]
スタッフになったときにまず何をしてほしいかなどなどをドキュメントとして公開しておきたい。

* Code of conduct
* 各種のリンク、Google ドキュメントの共有フォルダなど
* 何らかの登録が必要であればそれらについても

**Comment by miya0001** [comment]
ドキュメントの公開先はとりあえず [Wiki](https://github.com/space-apps-kushimoto/handbook/wiki) でいい？

**Comment by kwaka1208** [comment]
Wikiでいいと思います。
