### ISSUE TITLE
モデルロケットについて

### ISSUE THREAD

**Issue by miya0001** [space-apps-kushimoto/handbook#6]
山本さんより

---
モデルロケットの打ち上げとハッカソンをどう構成するか、考えたいです。
　通例のNASAからのテーマというのは、どんな内容なのでしょうか？
　また、NASAのオープンデータにはどのようなものがありますでしょうか？
　今回のハッカソンで作り上げるプログラムまたはシステムとモデルロケットの打ち上げがリンクできるのか？というのがあります。

そもそも、モデルロケットでできること

缶サット甲子園で用いるロケットエンジンと同じものを使うので、ロケットに収納できるものとしてはRaspberryPi一枚とバッテリーくらいです。
　打ち上げ後、約100m上空でモデルロケットより放出され落下します。パラシュートを付けますが、遠くに飛んで行ってロストしないように、放出後20秒くらいで落下させます。打ち上げから落下までの間に写真を撮ったり、データを取ったり、通信をしたりします。
　缶サットの枠から外れて、スマホを入れて打ち上げたり、小さなドローンを入れて放出後は自力で帰って来るとかも、危険でなければありかも知れません。

　ハッカソン時にモデルロケットで打ち上げて何かするというアイデア出しはしてもらって、うまいアイデアが出なくても、エキジビジョンとして二台くらい打ち上げを行なうという感じが現実的かなという気がしています。

　あと、「モデルロケットを打ち上げる」という話を広報してしまうと、ハッカソン関係無に見物ギャラリーが来てしまうという恐れがあります。100mくらいしか打ちあがらないとはいえ、打ち上げ時にロケットが横を向くと100m水平に飛んでくるので、ギャラリーは発射台から100mくらいは離れておいてもらう必要があります。

　もし、ハッカソンチームでモデルロケットを使いたいというチームがあれば、申請してもらって、そのチームだけ来てもらって、2日目の午前中くらいに打ち上げる感じでしょうか。

　打ち上げ費用のことも考えないといけないので、打ち上げに掛かる実費について藤木先生に聞いてみます。
　意見など、よろしくお願いします。

**Comment by miya0001** [comment]
当日の内容については NASA から連絡があることになっていますが、参加地域の申込みの締切が6月なのを考えると、7月になるまでテーマ等は確定しないと思います。

あと以下確認しないといけないかなと思います。

* 潮岬の望楼の芝は民間企業さんの私有地なので費用がかかる可能性がある（潮岬観光タワーさん？）
* 何らかの移動手段を用意する必要がある（会場はまだ未定）
* スタッフの人数が分散される可能性があるのでそこを検討しないといけない
* 週末なのでそもそも貸し切りが可能かどうかも確認が必要

**Comment by miya0001** [comment]
観光協会に問い合わせしたところ、「潮岬望楼の芝管理運営委員会」というのが役所内にあって、そこに相談できるとのことでした。

**Comment by tarosay** [comment]
桐蔭高校の藤木先生と話をしてきました。
内容を箇条書きします。

- NASA Space App Challengeハッカソンについて説明しました。若林さんがアップしてくれた去年の資料などを見せて内容を説明しました。
- モデルロケットはハッカソン中に打ち上げる方向で考えていると話しました。
- 「望楼の芝」民間なのでお金もかかるという話をしました。


藤木先生の話
- 和歌山にロケット打ち上げ場ができるなんてとてもいい話で、NASA Space App Challengeにも協力したいとモデルロケットも打ち上げたいという話しでした。
- 打ち上げスタッフに関しては、藤木先生と生徒が数人いれば現場は回るのではないかという話しでした。

モデルロケットとNASA Space App Challengeの連携について
- NASAからテーマが発表されたら、そのテーマとNASAのオープンデータと缶サットが連携したテーマを生徒たちに考えてもらい、それを持ってNASA Space App Challengeに生徒たちが臨むというストーリーでどうかという話しになりました。

缶サットでモデルロケットを打ち上げている他の高校についても、このような感じで挑戦してもらえればいいのではないでしょうか。

**Comment by tarosay** [comment]
モデルロケット打ち上げの費用について
- ロケットエンジン代 3本で3,150円。1回の打ち上げに3本を同時に使用。
- リカバリーワディング(不燃紙)代200円。1回の打ち上げに200円ほど。
- 発射台と発射装置: 学校にある機材を持ち込みます。
- 発射台の下には鉄板をひくので、エンジンの炎で芝が燃える心配はないそうです。
- 風対策について、モデルロケット発射時に風向きを考えて、敷地内に缶サットが落下するようにロケットを風上に向けて打ち上げるそうです。
- ロケットは手作りとなりますが、打ち上げ未経験のチームが打ち上げることになる場合は、ロケットは生徒さん達に手作りしてもらうかという話しをしていました。
